---
- name: download php7.3 source to compile
  get_url:
    url: https://www.php.net/distributions/{{ php7 }}
    dest: '{{ source_dir  }}'

- name: extract source php
  unarchive:
    src: '{{ source_dir }}/{{ php7 }}'
    dest: '{{ source_dir }}'
    remote_src: yes

- name: configure source php
  command: ./configure  '--prefix=/opt/{{ php_name }}' '--with-zlib-dir' '--with-freetype-dir' '--with-libxml-dir=/usr' '--enable-calendar' '--with-curl' '--with-mcrypt' '--with-gd' '--enable-inline-optimization' '--with-bz2' '--with-zlib' '--enable-sockets' '--enable-sysvsem' '--enable-sysvshm' '--enable-pcntl' '--enable-mbregex' '--with-mhash' '--enable-zip' '--with-pcre-regex' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-pdo-mysql' '--with-mysqli' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--enable-gd-native-ttf' '--with-openssl' '--with-fpm-user=nginx' '--with-fpm-group=nginx' '--with-libdir=lib64' '--enable-ftp' '--enable-opcache' '--enable-bcmath' '--enable-fpm' '--enable-mbstring'
  args:
    chdir: '{{ source_dir }}/{{ php_name }}'

- name: make install php
  shell: make && make install
  args:
    chdir: '{{ source_dir }}/{{ php_name }}'

- name: copy file php.ini
  copy:
    src: '{{ source_dir }}/{{ php_name }}/php.ini-production'
    dest: /opt/{{ php_name }}/lib/php.ini
    remote_src: yes

- name: change upload max
  lineinfile:
    path: /opt/{{ php_name }}/lib/php.ini
    regexp: 'upload_max_filesize ='
    line: 'upload_max_filesize = 256M'

- name: chage post file upload
  lineinfile:
    path: /opt/{{ php_name }}/lib/php.ini
    regexp: 'post_max_size ='
    line: 'post_max_size = 256M'

- name: copy php-fpm.conf file
  copy:
    src: /opt/{{ php_name }}/etc/php-fpm.conf.default
    dest: /opt/{{ php_name }}/etc/php-fpm.conf
    remote_src: yes

- name: edit php-fpm.conf file - edit pid
  lineinfile:
    path: /opt/{{ php_name }}/etc/php-fpm.conf
    regexp: "^;pid ="
    line: "pid = run/php-fpm.pid"
    
- name: edit php-fpm.conf file - edit include file .conf
  lineinfile:
    path: /opt/{{ php_name }}/etc/php-fpm.conf
    line: include=/opt/{{ php_name }}/etc/php-fpm.d/*.conf
  tags:
    - test
- name: copy start service file
  template:
    src: php-fpm-7.service
    dest: /lib/systemd/system/php-fpm-7.service

- name: create PHP pool handle socket
  template:
    src: www.conf
    dest: /opt/{{ php_name }}/etc/php-fpm.d/{{ server_name }}.conf
  tags:
    - test

- name: start php-fpm service
  service: name=php-fpm-7 state=started enabled=yes
