- name: LEMP Compile Nginx + PHP-FPM 7.3 + PHP-FPM 5.6 From Source + Mariadb + Wordpress
  hosts: appgroup
  become: yes
  become_method: sudo


  roles:

    - Dependencies
    - Nginx
    - Vhost
    - PHP-FPM
    - Mariadb
    - Wordpress

  tasks:
    - name: reboot all server
      reboot:
        reboot_timeout: 36
